### ISSUE TITLE
Langsam ladende Seiten (EN + DE)

### ISSUE THREAD

**Issue by evelyn-gius** [forTEXT/lab#2]
Problem: Aufbau dauert zu lange bei Publications und Team, bei letzterem verspringt außerdem der Text beim Laden der Bilder.

Mögliche Lösung: Für alle oder für alle nicht sehr(!) schnell ladenden Seiten statische Seiten generieren?

**Comment by Momamari** [comment]
Werde versuchen über lazyload o.ä die Publikationsseite schneller zu machen (auch auf deiner Seite). Bei der Teamseite liegt es eigentlich nur an den Bildern, die ich schon etwas komprimiert habe.

**Comment by evelyn-gius** [comment]
Die Bilder können auch kleiner sein, vermute ich. Falls das schneller Laden nicht klappt, sollte Plan B ein Lade-Icon auf(!) der enstprechenden Seite sein, das sich bewegt. Dann weiß man schon mal, da kommt noch was.

**Comment by Momamari** [comment]
Also das mit dem Lazyload u.ä. muss ich mir noch genauer anschauen. Teamseite sollte jetzt eigentlich schneller Laden und für alle Publikationsseiten habe ich jetzt erstmal ein Ladeicon eingebaut
