### ISSUE TITLE
Bilder Teammitglieder vereinheitlichen/anpassen

### ISSUE THREAD

**Issue by evelyn-gius** [forTEXT/lab#4]
- Gesichter einheitlich zentrieren (bei einheitlicher Größe) Default: Ausschnitt bei Dominik
- Bilder kleiner / ggf. quadratisch, damit Bild möglichst nicht größer als Text

**Comment by Momamari** [comment]
Bildausschnitte sind angepasst und Bilder so groß, dass der längste Text nicht über den Bildrändern "liegt". Gerne gucken, ob das so ok ist, oder noch quadratisch o.ä. geändert werden soll
